/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmsTermsRouteImport } from './routes/sms-terms'
import { Route as SmsOptinRouteImport } from './routes/sms-optin'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EstimateformRouteImport } from './routes/estimateform'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMetaCapiRouteImport } from './routes/api/meta-capi'
import { Route as ApiManychatRouteImport } from './routes/api/manychat'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const SmsTermsRoute = SmsTermsRouteImport.update({
  id: '/sms-terms',
  path: '/sms-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsOptinRoute = SmsOptinRouteImport.update({
  id: '/sms-optin',
  path: '/sms-optin',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateformRoute = EstimateformRouteImport.update({
  id: '/estimateform',
  path: '/estimateform',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaCapiRoute = ApiMetaCapiRouteImport.update({
  id: '/api/meta-capi',
  path: '/api/meta-capi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManychatRoute = ApiManychatRouteImport.update({
  id: '/api/manychat',
  path: '/api/manychat',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/estimate': typeof EstimateRoute
  '/estimateform': typeof EstimateformRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/sms-optin': typeof SmsOptinRoute
  '/sms-terms': typeof SmsTermsRoute
  '/api/manychat': typeof ApiManychatRoute
  '/api/meta-capi': typeof ApiMetaCapiRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/estimate': typeof EstimateRoute
  '/estimateform': typeof EstimateformRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/sms-optin': typeof SmsOptinRoute
  '/sms-terms': typeof SmsTermsRoute
  '/api/manychat': typeof ApiManychatRoute
  '/api/meta-capi': typeof ApiMetaCapiRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/estimate': typeof EstimateRoute
  '/estimateform': typeof EstimateformRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/sms-optin': typeof SmsOptinRoute
  '/sms-terms': typeof SmsTermsRoute
  '/api/manychat': typeof ApiManychatRoute
  '/api/meta-capi': typeof ApiMetaCapiRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/estimate'
    | '/estimateform'
    | '/privacy'
    | '/quiz'
    | '/sms-optin'
    | '/sms-terms'
    | '/api/manychat'
    | '/api/meta-capi'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/estimate'
    | '/estimateform'
    | '/privacy'
    | '/quiz'
    | '/sms-optin'
    | '/sms-terms'
    | '/api/manychat'
    | '/api/meta-capi'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/estimate'
    | '/estimateform'
    | '/privacy'
    | '/quiz'
    | '/sms-optin'
    | '/sms-terms'
    | '/api/manychat'
    | '/api/meta-capi'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EstimateRoute: typeof EstimateRoute
  EstimateformRoute: typeof EstimateformRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  SmsOptinRoute: typeof SmsOptinRoute
  SmsTermsRoute: typeof SmsTermsRoute
  ApiManychatRoute: typeof ApiManychatRoute
  ApiMetaCapiRoute: typeof ApiMetaCapiRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sms-terms': {
      id: '/sms-terms'
      path: '/sms-terms'
      fullPath: '/sms-terms'
      preLoaderRoute: typeof SmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-optin': {
      id: '/sms-optin'
      path: '/sms-optin'
      fullPath: '/sms-optin'
      preLoaderRoute: typeof SmsOptinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimateform': {
      id: '/estimateform'
      path: '/estimateform'
      fullPath: '/estimateform'
      preLoaderRoute: typeof EstimateformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-capi': {
      id: '/api/meta-capi'
      path: '/api/meta-capi'
      fullPath: '/api/meta-capi'
      preLoaderRoute: typeof ApiMetaCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manychat': {
      id: '/api/manychat'
      path: '/api/manychat'
      fullPath: '/api/manychat'
      preLoaderRoute: typeof ApiManychatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EstimateRoute: EstimateRoute,
  EstimateformRoute: EstimateformRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  SmsOptinRoute: SmsOptinRoute,
  SmsTermsRoute: SmsTermsRoute,
  ApiManychatRoute: ApiManychatRoute,
  ApiMetaCapiRoute: ApiMetaCapiRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
